export const weapons = [
  {
    Name: "Ancient Nord Battle Axe",
    Damage: "18",
    Weight: "22",
    Gold: "28",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Daedric Battleaxe",
    Damage: "25",
    Weight: "27",
    Gold: "2750",
    Upgrade: "Ebony Ingot",
    Perk: "Daedric",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbone Battleaxe",
    Damage: "26",
    Weight: "30",
    Gold: "3000",
    Upgrade: "Dragon Bone",
    Perk: "Dragon",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Drainblood Battleaxe",
    Damage: "21",
    Weight: "5",
    Gold: "266",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "-",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Dwarven Battleaxe",
    Damage: "20",
    Weight: "23",
    Gold: "300",
    Upgrade: "Ebony Ingot",
    Perk: "Dwarven",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Ebony Battleaxe",
    Damage: "23",
    Weight: "26",
    Gold: "1585",
    Upgrade: "Refined Moonstone",
    Perk: "Ebony",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Elven Battleaxe",
    Damage: "21",
    Weight: "24",
    Gold: "520",
    Upgrade: "Refined Malachite",
    Perk: "Elven",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Glass Battleaxe",
    Damage: "22",
    Weight: "25",
    Gold: "900",
    Upgrade: "Steel Ingot",
    Perk: "Glass",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Headsman's Axe",
    Damage: "17",
    Weight: "11",
    Gold: "15",
    Upgrade: "Iron Ingot",
    Perk: "-",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Honed Ancient Nord Battle Axe",
    Damage: "21",
    Weight: "25",
    Gold: "50",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Iron Battleaxe",
    Damage: "16",
    Weight: "20",
    Gold: "55",
    Upgrade: "Quicksilver Ingot",
    Perk: "None",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Nord Hero Battle Axe",
    Damage: "21",
    Weight: "20",
    Gold: "300",
    Upgrade: "Orichalcum Ingot",
    Perk: "Steel",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Nordic Battleaxe DR",
    Damage: "21",
    Weight: "23",
    Gold: "650",
    Upgrade: "Steel Ingot",
    Perk: "Advanced",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Orcish Battleaxe",
    Damage: "19",
    Weight: "25",
    Gold: "165",
    Upgrade: "Stalhrim",
    Perk: "Orcish",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Skyforge Steel Battleaxe",
    Damage: "21",
    Weight: "21",
    Gold: "150",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Stalhrim Battleaxe",
    Damage: "24",
    Weight: "25",
    Gold: "2150",
    Upgrade: "Steel Ingot",
    Perk: "Ebony",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Steel Battleaxe of Fiery Souls",
    Damage: "18",
    Weight: "21",
    Gold: "320",
    Upgrade: "Ebony Ingot",
    Perk: "Steel",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Steel Battleaxe",
    Damage: "18",
    Weight: "21",
    Gold: "100",
    Upgrade: "N/A",
    Perk: "Steel",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Rueful Axe",
    Damage: "22",
    Weight: "10",
    Gold: "1183",
    Upgrade: "None required",
    Perk: "None",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "The Woodsman's Friend",
    Damage: "17",
    Weight: "20",
    Gold: "28",
    Upgrade: "Ebony Ingot",
    Perk: "-",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Tsun's Battleaxe",
    Damage: "27",
    Weight: "36",
    Gold: "1000",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Wuuthrad",
    Damage: "25",
    Weight: "25",
    Gold: "2000",
    Upgrade: "Refined Moonstone",
    Perk: "-",
    Type: "Battleaxe",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Alessandra's Dagger",
    Damage: "5",
    Weight: "1",
    Gold: "10",
    Upgrade: "Ebony Ingot",
    Perk: "-",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Blade of Woe",
    Damage: "12",
    Weight: "7",
    Gold: "880",
    Upgrade: "Dragon Bone",
    Perk: "Steel",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Blade of Sacrifice",
    Damage: "10",
    Weight: "4",
    Gold: "144",
    Upgrade: "N/A",
    Perk: "None",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Bloodthorn",
    Damage: "8",
    Weight: "2.5",
    Gold: "183",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "Steel",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Borvir's Dagger",
    Damage: "8",
    Weight: "4",
    Gold: "18",
    Upgrade: "Ebony Ingot",
    Perk: "Elven",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Daedric Dagger",
    Damage: "11",
    Weight: "6",
    Gold: "500",
    Upgrade: "Refined Moonstone",
    Perk: "Daedric",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbone Dagger",
    Damage: "12",
    Weight: "6.5",
    Gold: "600",
    Upgrade: "Refined Malachite",
    Perk: "Dragon",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragon Priest Dagger",
    Damage: "6",
    Weight: "5",
    Gold: "9",
    Upgrade: "Iron Ingot",
    Perk: "-",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dwarven Dagger",
    Damage: "7",
    Weight: "3.5",
    Gold: "55",
    Upgrade: "N/A",
    Perk: "Dwarven",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ebony Dagger",
    Damage: "10",
    Weight: "5",
    Gold: "290",
    Upgrade: "N/A",
    Perk: "Ebony",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Elven Dagger",
    Damage: "8",
    Weight: "4",
    Gold: "95",
    Upgrade: "Ebony Ingot",
    Perk: "Elven",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Glass Dagger",
    Damage: "9",
    Weight: "4.5",
    Gold: "165",
    Upgrade: "Ebony Ingot",
    Perk: "Glass",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Iron Dagger",
    Damage: "4",
    Weight: "2",
    Gold: "10",
    Upgrade: "Quicksilver Ingot",
    Perk: "None",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Kahvozein's Fang",
    Damage: "6",
    Weight: "5",
    Gold: "9",
    Upgrade: "Orichalcum Ingot",
    Perk: "-",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Keening",
    Damage: "8",
    Weight: "4",
    Gold: "5",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Mehrunes' Razor",
    Damage: "11",
    Weight: "3",
    Gold: "860",
    Upgrade: "N/A",
    Perk: "None",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nettlebane",
    Damage: "6",
    Weight: "10",
    Gold: "5",
    Upgrade: "N/A",
    Perk: "None",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nordic Dagger",
    Damage: "8",
    Weight: "3.5",
    Gold: "115",
    Upgrade: "Stalhrim",
    Perk: "Advanced",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Orcish Dagger",
    Damage: "6",
    Weight: "3",
    Gold: "30",
    Upgrade: "Steel Ingot",
    Perk: "Orcish",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Rundi's Dagger",
    Damage: "5",
    Weight: "2.5",
    Gold: "18",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Shiv",
    Damage: "5",
    Weight: "2",
    Gold: "5",
    Upgrade: "Ebony Ingot",
    Perk: "-",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Skyforge Steel Dagger",
    Damage: "8",
    Weight: "2.5",
    Gold: "25",
    Upgrade: "Dragon Bone",
    Perk: "-",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Stalhrim Dagger",
    Damage: "10",
    Weight: "4.5",
    Gold: "395",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "Ebony",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Steel Dagger",
    Damage: "5",
    Weight: "2.5",
    Gold: "18",
    Upgrade: "Ebony Ingot",
    Perk: "Steel",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Valdr's Lucky Dagger",
    Damage: "5",
    Weight: "2.5",
    Gold: "15",
    Upgrade: "Refined Moonstone",
    Perk: "Steel",
    Type: "Dagger",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Daedric Mace",
    Damage: "16",
    Weight: "20",
    Gold: "1750",
    Upgrade: "Refined Malachite",
    Perk: "Daedric",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbone Mace",
    Damage: "17",
    Weight: "22",
    Gold: "2000",
    Upgrade: "Steel Ingot",
    Perk: "Dragon",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dwarven Mace",
    Damage: "12",
    Weight: "16",
    Gold: "190",
    Upgrade: "Iron Ingot",
    Perk: "Dwarven",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ebony Mace",
    Damage: "16",
    Weight: "19",
    Gold: "1000",
    Upgrade: "Iron Ingot",
    Perk: "Ebony",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Elven Mace",
    Damage: "13",
    Weight: "17",
    Gold: "330",
    Upgrade: "Iron Ingot",
    Perk: "Elven",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Glass Mace",
    Damage: "14",
    Weight: "18",
    Gold: "575",
    Upgrade: "Iron Ingot",
    Perk: "Glass",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Horksbane",
    Damage: "10",
    Weight: "14",
    Gold: "250",
    Upgrade: "Iron Ingot",
    Perk: "Steel",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Iron Mace",
    Damage: "9",
    Weight: "13",
    Gold: "35",
    Upgrade: "Iron Ingot",
    Perk: "None",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron Mace (Lvl 2-3)",
    Damage: "9",
    Weight: "13",
    Gold: "99",
    Upgrade: "Iron Ingot",
    Perk: "None",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron Mace (Lvl 4-5)",
    Damage: "9",
    Weight: "13",
    Gold: "133",
    Upgrade: "Ebony Ingot",
    Perk: "None",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron Mace (Lvl 6+)",
    Damage: "9",
    Weight: "13",
    Gold: "168",
    Upgrade: "Quicksilver Ingot",
    Perk: "None",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel Mace (Lvl 4-5)",
    Damage: "10",
    Weight: "14",
    Gold: "129",
    Upgrade: "Orichalcum Ingot",
    Perk: "None",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel Mace (Lvl 6-7)",
    Damage: "10",
    Weight: "14",
    Gold: "163",
    Upgrade: "Refined Moonstone",
    Perk: "None",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel Mace (Lvl 8+)",
    Damage: "10",
    Weight: "14",
    Gold: "198",
    Upgrade: "N/A",
    Perk: "None",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Mace of Molag Bal",
    Damage: "16",
    Weight: "18",
    Gold: "1257",
    Upgrade: "Stalhrim",
    Perk: "None",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nordic Mace",
    Damage: "13",
    Weight: "16",
    Gold: "410",
    Upgrade: "Steel Ingot",
    Perk: "Advanced",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Orcish Mace",
    Damage: "11",
    Weight: "15",
    Gold: "105",
    Upgrade: "Iron Ingot",
    Perk: "Orcish",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Prelate's Mace",
    Damage: "13",
    Weight: "7",
    Gold: "330",
    Upgrade: "Steel Ingot",
    Perk: "Elven",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Rusty Mace",
    Damage: "7",
    Weight: "13",
    Gold: "5",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Stalhrim Mace",
    Damage: "16",
    Weight: "18",
    Gold: "1375",
    Upgrade: "Ebony Ingot",
    Perk: "Ebony",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Steel Mace",
    Damage: "10",
    Weight: "14",
    Gold: "65",
    Upgrade: "Quicksilver Ingot",
    Perk: "Steel",
    Type: "Mace",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Akaviri Sword",
    Damage: "11",
    Weight: "10",
    Gold: "300",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Amren's Family Sword",
    Damage: "7",
    Weight: "9",
    Gold: "25",
    Upgrade: "Refined Malachite",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ancient Nord Sword",
    Damage: "8",
    Weight: "12",
    Gold: "13",
    Upgrade: "Refined Malachite",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Blades Sword",
    Damage: "11",
    Weight: "10",
    Gold: "300",
    Upgrade: "Refined Malachite",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Bloodscythe",
    Damage: "13",
    Weight: "10",
    Gold: "1859",
    Upgrade: "Refined Malachite",
    Perk: "Daedric",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Bolar's Oathblade",
    Damage: "11",
    Weight: "10",
    Gold: "1014",
    Upgrade: "Refined Malachite",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ceremonial Sword",
    Damage: "8",
    Weight: "12",
    Gold: "5",
    Upgrade: "Refined Malachite",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Chillrend (Lv 1-10)",
    Damage: "10",
    Weight: "11",
    Gold: "552",
    Upgrade: "Ebony Ingot",
    Perk: "Glass",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Chillrend (Lvl 11-18)",
    Damage: "11",
    Weight: "12",
    Gold: "635",
    Upgrade: "Ebony Ingot",
    Perk: "Glass",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Chillrend (Lvl 19-26)",
    Damage: "12",
    Weight: "13",
    Gold: "872",
    Upgrade: "Quicksilver Ingot",
    Perk: "Glass",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Chillrend (Lvl 27-35)",
    Damage: "13",
    Weight: "14",
    Gold: "846",
    Upgrade: "Quicksilver Ingot",
    Perk: "Glass",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Chillrend (Lvl 36-45)",
    Damage: "14",
    Weight: "15",
    Gold: "1111",
    Upgrade: "Quicksilver Ingot",
    Perk: "Glass",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Chillrend (Lvl 46+)",
    Damage: "15",
    Weight: "16",
    Gold: "1442",
    Upgrade: "Quicksilver Ingot",
    Perk: "Glass",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Daedric Sword",
    Damage: "14",
    Weight: "16",
    Gold: "1250",
    Upgrade: "Quicksilver Ingot",
    Perk: "Daedric",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dawnbreaker",
    Damage: "12",
    Weight: "10",
    Gold: "740",
    Upgrade: "Dragon Bone",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbane (Lvl 1-18)",
    Damage: "10",
    Weight: "10",
    Gold: "789",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbane (Lvl 19-26)",
    Damage: "11",
    Weight: "11",
    Gold: "1046",
    Upgrade: "Ebony Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbane (Lvl 27-35)",
    Damage: "12",
    Weight: "12",
    Gold: "1189",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbane (Lvl 36-45)",
    Damage: "13",
    Weight: "13",
    Gold: "1860",
    Upgrade: "Refined Moonstone",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbane (Lvl 46+)",
    Damage: "14",
    Weight: "14",
    Gold: "2596",
    Upgrade: "Chaurus Chitin",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbone Sword",
    Damage: "15",
    Weight: "19",
    Gold: "1500",
    Upgrade: "Steel Ingot",
    Perk: "Dragon",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Drainheart Sword",
    Damage: "11",
    Weight: "3",
    Gold: "73",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dwarven Sword",
    Damage: "10",
    Weight: "12",
    Gold: "135",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ebony Sword",
    Damage: "13",
    Weight: "15",
    Gold: "720",
    Upgrade: "Steel Ingot",
    Perk: "Ebony",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Eduj",
    Damage: "11",
    Weight: "9",
    Gold: "300",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Elven Sword",
    Damage: "11",
    Weight: "13",
    Gold: "235",
    Upgrade: "Steel Ingot",
    Perk: "Elven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Falmer Sword",
    Damage: "10",
    Weight: "18",
    Gold: "67",
    Upgrade: "3 Ectoplasm",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Forsworn Sword",
    Damage: "10",
    Weight: "13",
    Gold: "70",
    Upgrade: "Refined Malachite",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Gauldur Blackblade (Lvl 1-11)",
    Damage: "8",
    Weight: "12",
    Gold: "234",
    Upgrade: "Refined Malachite",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Gauldur Blackblade (Lvl 12-18)",
    Damage: "8",
    Weight: "12",
    Gold: "465",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Gauldur Blackblade (Lvl 19-26)",
    Damage: "11",
    Weight: "15",
    Gold: "669",
    Upgrade: "Refined Moonstone",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Gauldur Blackblade (Lvl 27-35)",
    Damage: "11",
    Weight: "15",
    Gold: "975",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Gauldur Blackblade (Lvl 36+)",
    Damage: "11",
    Weight: "15",
    Gold: "1286",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ghostblade",
    Damage: "8",
    Weight: "1",
    Gold: "300",
    Upgrade: "Iron Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Glass Sword",
    Damage: "12",
    Weight: "14",
    Gold: "410",
    Upgrade: "Iron Ingot",
    Perk: "Glass",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Grimsever",
    Damage: "12",
    Weight: "14",
    Gold: "727",
    Upgrade: "Iron Ingot",
    Perk: "Glass",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Harkon's Sword",
    Damage: "8",
    Weight: "9",
    Gold: "1472",
    Upgrade: "Iron Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Herebane's Courage",
    Damage: "11",
    Weight: "13",
    Gold: "639",
    Upgrade: "Steel Ingot",
    Perk: "Elven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Hjalti's Sword",
    Damage: "8",
    Weight: "12",
    Gold: "13",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Honed Ancient Nord Sword",
    Damage: "11",
    Weight: "15",
    Gold: "23",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Honed Falmer Sword",
    Damage: "12",
    Weight: "18",
    Gold: "205",
    Upgrade: "Daedra HeartEbony Ingot",
    Perk: "-",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Imperial Sword",
    Damage: "8",
    Weight: "10",
    Gold: "23",
    Upgrade: "Ebony Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Iron Sword",
    Damage: "7",
    Weight: "9",
    Gold: "25",
    Upgrade: "Ebony Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron Sword (Lvl 2-3)",
    Damage: "7",
    Weight: "9",
    Gold: "89",
    Upgrade: "Ebony Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron Sword (Lvl 4-5)",
    Damage: "7",
    Weight: "9",
    Gold: "123",
    Upgrade: "Ebony Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron Sword (Lvl 6+)",
    Damage: "7",
    Weight: "9",
    Gold: "158",
    Upgrade: "Ebony Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel Sword (Lvl 4-5)",
    Damage: "8",
    Weight: "10",
    Gold: "69",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel Sword (Lvl 6-7)",
    Damage: "8",
    Weight: "10",
    Gold: "103",
    Upgrade: "Quicksilver Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel Sword (Lvl 8+)",
    Damage: "8",
    Weight: "10",
    Gold: "138",
    Upgrade: "Orichalcum Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Miraak's Sword",
    Damage: "16",
    Weight: "3",
    Gold: "427",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nightingale Blade (Lvl1-18)",
    Damage: "10",
    Weight: "11",
    Gold: "426",
    Upgrade: "Steel Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nightingale Blade (Lvl 19-26)",
    Damage: "11",
    Weight: "12",
    Gold: "851",
    Upgrade: "Steel Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nightingale Blade (Lvl 27-35)",
    Damage: "12",
    Weight: "13",
    Gold: "1424",
    Upgrade: "Steel Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nightingale Blade (Lvl 36-45)",
    Damage: "13",
    Weight: "14",
    Gold: "2248",
    Upgrade: "Steel Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nightingale Blade (Lvl 46+)",
    Damage: "14",
    Weight: "15",
    Gold: "1665",
    Upgrade: "Stalhrim",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nord Hero Sword",
    Damage: "11",
    Weight: "9",
    Gold: "135",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nordic Sword",
    Damage: "11",
    Weight: "12",
    Gold: "290",
    Upgrade: "Ebony Ingot",
    Perk: "Advanced",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Orcish Sword",
    Damage: "9",
    Weight: "11",
    Gold: "75",
    Upgrade: "Steel Ingot",
    Perk: "Orcish",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Phantom Sword",
    Damage: "1",
    Weight: "0",
    Gold: "0",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Queen Freydis's Sword",
    Damage: "8",
    Weight: "10",
    Gold: "45",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Red Eagle's Bane",
    Damage: "11",
    Weight: "15",
    Gold: "100",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Red Eagle's Fury",
    Damage: "8",
    Weight: "12",
    Gold: "97",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Scimitar",
    Damage: "11",
    Weight: "10",
    Gold: "5",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Silver Sword",
    Damage: "8",
    Weight: "7",
    Gold: "100",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Skyforge Steel Sword",
    Damage: "11",
    Weight: "10",
    Gold: "70",
    Upgrade: "Firewood",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Stalhrim Sword",
    Damage: "13",
    Weight: "14",
    Gold: "985",
    Upgrade: "Steel Ingot",
    Perk: "Ebony",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Steel Sword",
    Damage: "8",
    Weight: "10",
    Gold: "45",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Soulrender",
    Damage: "13",
    Weight: "10",
    Gold: "1000",
    Upgrade: "Ebony Ingot",
    Perk: "Daedric",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "The Pale Blade (Lvl 1-5)",
    Damage: "8",
    Weight: "12",
    Gold: "169",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "The Pale Blade (Lvl 6-11)",
    Damage: "8",
    Weight: "12",
    Gold: "286",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "The Pale Blade (Lvl 12-18)",
    Damage: "11",
    Weight: "15",
    Gold: "452",
    Upgrade: "Dragon Bone",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "The Pale Blade (Lvl 19-26)",
    Damage: "11",
    Weight: "15",
    Gold: "667",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "The Pale Blade (Lvl 27+)",
    Damage: "11",
    Weight: "15",
    Gold: "914",
    Upgrade: "Ebony Ingot",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Vilkas's Sword",
    Damage: "11",
    Weight: "10",
    Gold: "70",
    Upgrade: "Refined Moonstone",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Windshear",
    Damage: "11",
    Weight: "10",
    Gold: "40",
    Upgrade: "Chaurus Chitin",
    Perk: "Steel",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Wooden Sword",
    Damage: "2",
    Weight: "3",
    Gold: "25",
    Upgrade: "Steel Ingot",
    Perk: "None",
    Type: "Sword",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ancient Nord War Axe",
    Damage: "9",
    Weight: "14",
    Gold: "15",
    Upgrade: "Iron Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ancient Nordic Pickaxe",
    Damage: "5",
    Weight: "10",
    Gold: "500",
    Upgrade: "Refined Malachite",
    Perk: "–",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ceremonial Axe",
    Damage: "9",
    Weight: "14",
    Gold: "5",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Daedric War Axe",
    Damage: "15",
    Weight: "18",
    Gold: "1500",
    Upgrade: "Iron Ingot",
    Perk: "Daedric",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dawnguard Rune Axe",
    Damage: "11",
    Weight: "13",
    Gold: "175",
    Upgrade: "Iron Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dawnguard War Axe",
    Damage: "11",
    Weight: "13",
    Gold: "55",
    Upgrade: "Iron Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbone War Axe",
    Damage: "16",
    Weight: "21",
    Gold: "1700",
    Upgrade: "Iron Ingot",
    Perk: "Dragon",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Dwarven War Axe",
    Damage: "11",
    Weight: "14",
    Gold: "165",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ebony War Axe",
    Damage: "15",
    Weight: "17",
    Gold: "865",
    Upgrade: "Steel Ingot",
    Perk: "Ebony",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Elven War Axe",
    Damage: "12",
    Weight: "15",
    Gold: "280",
    Upgrade: "Steel Ingot",
    Perk: "Elven",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Falmer War Axe",
    Damage: "11",
    Weight: "21",
    Gold: "82",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Forsworn Axe",
    Damage: "11",
    Weight: "15",
    Gold: "90",
    Upgrade: "Quicksilver Ingot",
    Perk: "Glass",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ghorbash's Ancestral Axe",
    Damage: "8",
    Weight: "11",
    Gold: "30",
    Upgrade: "Iron Ingot",
    Perk: "–",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Glass War Axe",
    Damage: "14",
    Weight: "16",
    Gold: "490",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Hoarfrost",
    Damage: "5",
    Weight: "10",
    Gold: "946",
    Upgrade: "Orichalcum Ingot",
    Perk: "–",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Honed Draugr War Axe",
    Damage: "11",
    Weight: "16",
    Gold: "27",
    Upgrade: "Steel Ingot",
    Perk: "–",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Honed Falmer War Axe",
    Damage: "13",
    Weight: "21",
    Gold: "245",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Illusory War Axe",
    Damage: "1",
    Weight: "14",
    Gold: "15",
    Upgrade: "Stalhrim",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Iron War Axe",
    Damage: "8",
    Weight: "11",
    Gold: "30",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron War Axe (Lvl 2-3)",
    Damage: "8",
    Weight: "11",
    Gold: "94",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron War Axe (Lvl 4-5)",
    Damage: "8",
    Weight: "11",
    Gold: "128",
    Upgrade: "Steel Ingot",
    Perk: "Advanced",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Iron War Axe (Lvl 6+)",
    Damage: "8",
    Weight: "11",
    Gold: "163",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel War Axe (Lvl 2-3)",
    Damage: "9",
    Weight: "12",
    Gold: "119",
    Upgrade: "Silver Ingot",
    Perk: "Orcish",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel War Axe (Lvl 4-5)",
    Damage: "9",
    Weight: "12",
    Gold: "153",
    Upgrade: "Ebony Ingot",
    Perk: "–",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Lunar Steel War Axe (Lvl 6+)",
    Damage: "9",
    Weight: "12",
    Gold: "188",
    Upgrade: "Dragon Bone",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nord Hero War Axe",
    Damage: "12",
    Weight: "11",
    Gold: "165",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "Ebony",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Nordic War Axe",
    Damage: "12",
    Weight: "14",
    Gold: "350",
    Upgrade: "Ebony Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Notched Pickaxe",
    Damage: "5",
    Weight: "10",
    Gold: "303",
    Upgrade: "Refined Moonstone",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Okin",
    Damage: "12",
    Weight: "11",
    Gold: "320",
    Upgrade: "Refined Malachite",
    Perk: "–",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Orcish War Axe",
    Damage: "10",
    Weight: "13",
    Gold: "90",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Pickaxe",
    Damage: "5",
    Weight: "10",
    Gold: "5",
    Upgrade: "Iron Ingot",
    Perk: "Steel",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Poacher's Axe",
    Damage: "5",
    Weight: "10",
    Gold: "32",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Skyforge Steel War Axe",
    Damage: "12",
    Weight: "12",
    Gold: "80",
    Upgrade: "Quicksilver Ingot",
    Perk: "Daedric",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Stalhrim War Axe",
    Damage: "15",
    Weight: "16",
    Gold: "1180",
    Upgrade: "Orichalcum Ingot",
    Perk: "Dragon",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Steel War Axe",
    Damage: "9",
    Weight: "12",
    Gold: "55",
    Upgrade: "Steel Ingot",
    Perk: "Dwarven",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ulfric's War Axe",
    Damage: "9",
    Weight: "12",
    Gold: "55",
    Upgrade: "Stalhrim",
    Perk: "Ebony",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Woodcutter's Axe",
    Damage: "5",
    Weight: "10",
    Gold: "5",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "War Axe",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Fork",
    Damage: "1",
    Weight: "0.5",
    Gold: "5",
    Upgrade: "Steel Ingot",
    Perk: "Elven",
    Type: "Silverware",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Knife",
    Damage: "2",
    Weight: "0.5",
    Gold: "1",
    Upgrade: "Iron Ingot",
    Perk: "Glass",
    Type: "Silverware",
    Category: "One-Handed",
    Speed: "",
  },
  {
    Name: "Ancient Nord Greatsword",
    Damage: "17",
    Weight: "18",
    Gold: "35",
    Upgrade: "Ebony Ingot",
    Perk: "Dwarven",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Balgruuf's Greatsword",
    Damage: "17",
    Weight: "17",
    Gold: "200",
    Upgrade: "Steel Ingot",
    Perk: "None",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Bloodskal Blade DR",
    Damage: "21",
    Weight: "16",
    Gold: "1250",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Daedric Greatsword",
    Damage: "24",
    Weight: "23",
    Gold: "2500",
    Upgrade: "Dragon Bone",
    Perk: "Advanced",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbone Greatsword",
    Damage: "25",
    Weight: "27",
    Gold: "2725",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "Orcish",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Dwarven Greatsword",
    Damage: "19",
    Weight: "19",
    Gold: "270",
    Upgrade: "Ebony Ingot",
    Perk: "-",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Ebony Greatsword",
    Damage: "22",
    Weight: "22",
    Gold: "1440",
    Upgrade: "Refined Moonstone",
    Perk: "Steel",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Ebony Blade",
    Damage: "11",
    Weight: "10",
    Gold: "2000",
    Upgrade: "Refined Malachite",
    Perk: "Ebony",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Elven Greatsword",
    Damage: "20",
    Weight: "20",
    Gold: "470",
    Upgrade: "Iron Ingot",
    Perk: "Steel",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Glass Greatsword",
    Damage: "21",
    Weight: "22",
    Gold: "820",
    Upgrade: "Quicksilver Ingot",
    Perk: "Steel",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Honed Ancient Nord Greatsword",
    Damage: "20",
    Weight: "21",
    Gold: "63",
    Upgrade: "Orichalcum Ingot",
    Perk: "None",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Iron Greatsword",
    Damage: "15",
    Weight: "16",
    Gold: "50",
    Upgrade: "Orichalcum Ingot",
    Perk: "-",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Nord Hero Greatsword",
    Damage: "20",
    Weight: "16",
    Gold: "250",
    Upgrade: "Stalhrim",
    Perk: "Daedric",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Nordic Greatsword DR",
    Damage: "20",
    Weight: "19",
    Gold: "585",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Orcish Greatsword",
    Damage: "18",
    Weight: "18",
    Gold: "75",
    Upgrade: "Orichalcum Ingot",
    Perk: "Steel",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Silver Greatsword",
    Damage: "17",
    Weight: "12",
    Gold: "160",
    Upgrade: "Steel Ingot",
    Perk: "Dragon",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Skyforge Steel Greatsword",
    Damage: "20",
    Weight: "17",
    Gold: "140",
    Upgrade: "Ebony Ingot",
    Perk: "Dwarven",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Stalhrim Greatsword",
    Damage: "23",
    Weight: "21",
    Gold: "1970",
    Upgrade: "Steel Ingot",
    Perk: "Ebony",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Steel Greatsword",
    Damage: "17",
    Weight: "17",
    Gold: "90",
    Upgrade: "Steel Ingot",
    Perk: "Elven",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Stormfang",
    Damage: "17",
    Weight: "17",
    Gold: "1175",
    Upgrade: "Refined Moonstone",
    Perk: "Glass",
    Type: "Greatsword",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Aegisbane",
    Damage: "18",
    Weight: "24",
    Gold: "180",
    Upgrade: "Steel Ingot",
    Perk: "None",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Champion's Cudgel",
    Damage: "24",
    Weight: "27",
    Gold: "1767",
    Upgrade: "Ebony Ingot",
    Perk: "Advanced",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Daedric Warhammer",
    Damage: "27",
    Weight: "31",
    Gold: "4000",
    Upgrade: "Dragon Bone",
    Perk: "Orcish",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Dawnguard Warhammer",
    Damage: "22",
    Weight: "26",
    Gold: "110",
    Upgrade: "Leather Strips",
    Perk: "Orcish",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Dawnguard Rune Hammer",
    Damage: "22",
    Weight: "26",
    Gold: "500",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "Ebony",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Dragonbone Warhammer",
    Damage: "28",
    Weight: "33",
    Gold: "4275",
    Upgrade: "Ebony Ingot",
    Perk: "Steel",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Dwarven Warhammer",
    Damage: "22",
    Weight: "27",
    Gold: "325",
    Upgrade: "Ebony Ingot",
    Perk: "Orcish",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Ebony Warhammer",
    Damage: "25",
    Weight: "30",
    Gold: "1725",
    Upgrade: "Refined Moonstone",
    Perk: "Steel",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Elven Warhammer",
    Damage: "23",
    Weight: "28",
    Gold: "565",
    Upgrade: "Chaurus Chitin",
    Perk: "None",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Glass Warhammer",
    Damage: "24",
    Weight: "29",
    Gold: "985",
    Upgrade: "Refined Moonstone",
    Perk: "Steel",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Iron Warhammer",
    Damage: "18",
    Weight: "24",
    Gold: "60",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Nordic Warhammer",
    Damage: "23",
    Weight: "27",
    Gold: "700",
    Upgrade: "Iron Ingot",
    Perk: "Elven",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Orcish Warhammer",
    Damage: "21",
    Weight: "26",
    Gold: "180",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Shagrol's Warhammer",
    Damage: "21",
    Weight: "26",
    Gold: "200",
    Upgrade: "Steel Ingot",
    Perk: "Daedric",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Stalhrim Warhammer",
    Damage: "26",
    Weight: "29",
    Gold: "2850",
    Upgrade: "Steel Ingot",
    Perk: "Dragon",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Steel Warhammer",
    Damage: "20",
    Weight: "25",
    Gold: "110",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "The Longhammer",
    Damage: "21",
    Weight: "18",
    Gold: "90",
    Upgrade: "Steel Ingot",
    Perk: "Steel",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Trollsbane",
    Damage: "20",
    Weight: "25",
    Gold: "121",
    Upgrade: "Refined Malachite",
    Perk: "Dwarven",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Volendrung",
    Damage: "25",
    Weight: "26",
    Gold: "1843",
    Upgrade: "Refined Malachite",
    Perk: "Dwarven",
    Type: "Warhammer",
    Category: "Two-Handed",
    Speed: "",
  },
  {
    Name: "Ancient Nord Bow",
    Damage: "8",
    Weight: "12",
    Gold: "45",
    Upgrade: "Leather Strips",
    Perk: "Ebony",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Angi's Bow",
    Damage: "7",
    Weight: "7",
    Gold: "50",
    Upgrade: "Steel Ingot",
    Perk: "Elven",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.937",
  },
  {
    Name: "Auriel's Bow DG",
    Damage: "13",
    Weight: "11",
    Gold: "1000",
    Upgrade: "Firewood",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "1",
  },
  {
    Name: "Bow of the Hunt",
    Damage: "10",
    Weight: "7",
    Gold: "434",
    Upgrade: "Steel Ingot",
    Perk: "-",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.937",
  },
  {
    Name: "Daedric Bow",
    Damage: "19",
    Weight: "18",
    Gold: "2500",
    Upgrade: "Quicksilver Ingot",
    Perk: "Elven",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.5",
  },
  {
    Name: "Dragonbone Bow DG",
    Damage: "20",
    Weight: "20",
    Gold: "2725",
    Upgrade: "Orichalcum Ingot",
    Perk: "Steel",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.75",
  },
  {
    Name: "Drainspell Bow",
    Damage: "14",
    Weight: "6",
    Gold: "458",
    Upgrade: "Stalhrim",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Dravin's Bow",
    Damage: "7",
    Weight: "7",
    Gold: "50",
    Upgrade: "Ebony Ingot",
    Perk: "Dwarven",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.937",
  },
  {
    Name: "Dwarven Bow",
    Damage: "12",
    Weight: "10",
    Gold: "270",
    Upgrade: "Ebony Ingot",
    Perk: "Dwarven",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.75",
  },
  {
    Name: "Dwarven Black Bow of Fate DR",
    Damage: "13",
    Weight: "10",
    Gold: "1446",
    Upgrade: "Ebony Ingot",
    Perk: "Dwarven",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.75",
  },
  {
    Name: "Ebony Bow",
    Damage: "17",
    Weight: "16",
    Gold: "1440",
    Upgrade: "Ebony Ingot",
    Perk: "Dwarven",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.562",
  },
  {
    Name: "Elven Bow",
    Damage: "13",
    Weight: "12",
    Gold: "470",
    Upgrade: "Ebony Ingot",
    Perk: "Dwarven",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.687",
  },
  {
    Name: "Falmer Bow",
    Damage: "12",
    Weight: "15",
    Gold: "135",
    Upgrade: "Dwarven Metal Ingot",
    Perk: "Glass",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.75",
  },
  {
    Name: "Falmer Supple Bow",
    Damage: "15",
    Weight: "20",
    Gold: "410",
    Upgrade: "Steel Ingot",
    Perk: "Glass",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.75",
  },
  {
    Name: "Firiniel's End",
    Damage: "13",
    Weight: "12",
    Gold: "785",
    Upgrade: "Dwarven metal ingot",
    Perk: "Steel",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.687",
  },
  {
    Name: "Forsworn Bow",
    Damage: "12",
    Weight: "11",
    Gold: "145",
    Upgrade: "Steel Ingot",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Froki's Bow",
    Damage: "6",
    Weight: "5",
    Gold: "307",
    Upgrade: "Dwarven metal ingot",
    Perk: "-",
    Type: "Bow",
    Category: "Archery",
    Speed: "1",
  },
  {
    Name: "Gauldur Blackbow",
    Damage: "8",
    Weight: "12",
    Gold: "253",
    Upgrade: "",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Gauldur Blackbow",
    Damage: "8",
    Weight: "12",
    Gold: "407",
    Upgrade: "",
    Perk: "-",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Gauldur Blackbow",
    Damage: "14",
    Weight: "18",
    Gold: "530",
    Upgrade: "",
    Perk: "Advanced",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Gauldur Blackbow",
    Damage: "14",
    Weight: "18",
    Gold: "750",
    Upgrade: "",
    Perk: "Orcish",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Gauldur Blackbow",
    Damage: "14",
    Weight: "18",
    Gold: "972",
    Upgrade: "",
    Perk: "Ebony",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Glass Bow",
    Damage: "15",
    Weight: "14",
    Gold: "820",
    Upgrade: "",
    Perk: "-",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.625",
  },
  {
    Name: "Glass Bow of the Stag Prince DR",
    Damage: "16",
    Weight: "14",
    Gold: "375",
    Upgrade: "",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.625",
  },
  {
    Name: "Hunting Bow",
    Damage: "7",
    Weight: "7",
    Gold: "50",
    Upgrade: "",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.937",
  },
  {
    Name: "Imperial Bow",
    Damage: "9",
    Weight: "8",
    Gold: "90",
    Upgrade: "",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.75",
  },
  {
    Name: "Karliah's Bow",
    Damage: "25",
    Weight: "9",
    Gold: "5",
    Upgrade: "",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.625",
  },
  {
    Name: "Long Bow",
    Damage: "6",
    Weight: "5",
    Gold: "30",
    Upgrade: "",
    Perk: "None",
    Type: "Bow",
    Category: "Archery",
    Speed: "1",
  },
  {
    Name: "Nord Hero Bow",
    Damage: "11",
    Weight: "7",
    Gold: "200",
    Upgrade: "",
    Perk: "Dwarven",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Nordic Bow DR",
    Damage: "13",
    Weight: "11",
    Gold: "580",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.6875",
  },
  {
    Name: "Orcish Bow",
    Damage: "10",
    Weight: "9",
    Gold: "150",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.812",
  },
  {
    Name: "Stalhrim Bow DR",
    Damage: "17",
    Weight: "15",
    Gold: "1800",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.5625",
  },
  {
    Name: "Supple Ancient Nord Bow",
    Damage: "14",
    Weight: "18",
    Gold: "235",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.875",
  },
  {
    Name: "Nightingale Bow",
    Damage: "12",
    Weight: "9",
    Gold: "493",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.5",
  },
  {
    Name: "Nightingale Bow",
    Damage: "13",
    Weight: "11",
    Gold: "838",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.5",
  },
  {
    Name: "Nightingale Bow",
    Damage: "15",
    Weight: "13",
    Gold: "1409",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.5",
  },
  {
    Name: "Nightingale Bow",
    Damage: "17",
    Weight: "15",
    Gold: "2240",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.5",
  },
  {
    Name: "Nightingale Bow",
    Damage: "19",
    Weight: "18",
    Gold: "3405",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "0.5",
  },
  {
    Name: "Zephyr DG",
    Damage: "12",
    Weight: "10",
    Gold: "670",
    Upgrade: "",
    Perk: "",
    Type: "Bow",
    Category: "Archery",
    Speed: "1",
  },
  {
    Name: "Ancient Nord Arrow",
    Damage: "10",
    Weight: "0",
    Gold: "1",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Bloodcursed Elven Arrow DG",
    Damage: "16",
    Weight: "0",
    Gold: "6",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Daedric Arrow",
    Damage: "24",
    Weight: "0",
    Gold: "8",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Dragonbone Arrow DG",
    Damage: "25",
    Weight: "0",
    Gold: "9",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Dwarven Arrow",
    Damage: "14",
    Weight: "0",
    Gold: "4",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Dwarven Sphere Centurion Arrow",
    Damage: "20",
    Weight: "0",
    Gold: "0",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Ebony Arrow",
    Damage: "20",
    Weight: "0",
    Gold: "7",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Elven Arrow",
    Damage: "16",
    Weight: "0",
    Gold: "5",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Falmer Arrow",
    Damage: "7",
    Weight: "0",
    Gold: "1",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Forsworn Arrow",
    Damage: "7",
    Weight: "0",
    Gold: "1",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Glass Arrow",
    Damage: "18",
    Weight: "0",
    Gold: "6",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Iron Arrow",
    Damage: "8",
    Weight: "0",
    Gold: "1",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Nordic Arrow DR",
    Damage: "14",
    Weight: "0",
    Gold: "4",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Orcish Arrow",
    Damage: "12",
    Weight: "0",
    Gold: "3",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Practice Arrow",
    Damage: "0",
    Weight: "0",
    Gold: "0",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Riekling Spear DR",
    Damage: "10",
    Weight: "0",
    Gold: "2",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Rusty Arrow",
    Damage: "4",
    Weight: "0",
    Gold: "0",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Stalhrim Arrow DR",
    Damage: "20",
    Weight: "0",
    Gold: "7",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Steel Arrow",
    Damage: "10",
    Weight: "0",
    Gold: "2",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Sunhallowed Elven Arrow DG",
    Damage: "16",
    Weight: "0",
    Gold: "16",
    Upgrade: "",
    Perk: "",
    Type: "Arrow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Crossbow",
    Damage: "19",
    Weight: "14",
    Gold: "120",
    Upgrade: "",
    Perk: "",
    Type: "Crossbow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Dwarven Crossbow",
    Damage: "22",
    Weight: "20",
    Gold: "350",
    Upgrade: "",
    Perk: "",
    Type: "Crossbow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Enhanced Crossbow",
    Damage: "19",
    Weight: "15",
    Gold: "200",
    Upgrade: "",
    Perk: "",
    Type: "Crossbow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Enhanced Dwarven Crossbow",
    Damage: "22",
    Weight: "21",
    Gold: "550",
    Upgrade: "",
    Perk: "",
    Type: "Crossbow",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Steel Bolt",
    Damage: "10",
    Weight: "0",
    Gold: "1",
    Upgrade: "",
    Perk: "",
    Type: "Bolt",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Dwarven Bolt",
    Damage: "14",
    Weight: "0",
    Gold: "3",
    Upgrade: "",
    Perk: "",
    Type: "Bolt",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Exploding Steel Bolt of Fire",
    Damage: "10",
    Weight: "0",
    Gold: "5",
    Upgrade: "",
    Perk: "",
    Type: "Bolt",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Exploding Steel Bolt of Ice",
    Damage: "10",
    Weight: "0",
    Gold: "5",
    Upgrade: "",
    Perk: "",
    Type: "Bolt",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Exploding Steel Bolt of Shock",
    Damage: "10",
    Weight: "0",
    Gold: "5",
    Upgrade: "",
    Perk: "",
    Type: "Bolt",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Exploding Dwarven Bolt of Fire",
    Damage: "14",
    Weight: "0",
    Gold: "15",
    Upgrade: "",
    Perk: "",
    Type: "Bolt",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Exploding Dwarven Bolt of Ice",
    Damage: "14",
    Weight: "0",
    Gold: "15",
    Upgrade: "",
    Perk: "",
    Type: "Bolt",
    Category: "Archery",
    Speed: "",
  },
  {
    Name: "Exploding Dwarven Bolt of Shock",
    Damage: "14",
    Weight: "0",
    Gold: "15",
    Upgrade: "",
    Perk: "",
    Type: "Bolt",
    Category: "Archery",
    Speed: "",
  },
];
